apiVersion: apps/v1
kind: Deployment
metadata:
  name: family-day-web
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: web
          imagePullPolicy: Always