---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: family-day-prod
spec:
  encryptedData:
    .dockerconfigjson: AgB44fyhjRsyRyiw5C5LL6GlK+GGpGP/1yElpyRJGQO8NLdqnqAhGZYIK15kcWVR2XSnablg8Es0MFpP6aHky3y+ObNvpwpkdqTDcqaMUxEcBKZe8eow67l7h0RwNwk86NRIcocMbShEtHMeEuR72br74ZKI91rlLSYI6PafFoI1Wla0zRAS9s7QZjv1RaqI9JFQ3xtpvZ+GZbtwaBGt1nUeuK2VkaSwNFhqxo09yHNGXpF1swA9MS5pv9fgKpUF7VQ2DD+YV4zFHl7Qmwo7CZdc3FxKln5dSN45cZR3KTzB5xZmtQueWzMDgAF32tK0BUWv6uujtUcit8tLU0GA/DJHz6NQI/LbHSehqSiBmnJBpExqftAyc0WqRQGCqGpaollOTmF67UUCT1hxlZE0vZpt7PMHPnn0s3MHK9IqLlxCHq4FN2iLt/E+rZTUigur5ARX2zS0UZL0y1WQT940U+aWPbmTZWHIkA1MvVI004OwXIGHyTrF78ODEKHUrRv8sn2s/KL51PyGULesanGGpTpjaBNw2a1RgyERZaAluLYlkqHgr9XG4ccZSoVjkNbBRG5v26+mANs4LG+nZXMaRO2nIDYLNwUKmKYcsjaBtPicAKWOnv3oAYKoF2ISsiyLQCJjtyncX4M5KdTao/NNLi0jEeXkj/6IpsM/Q8lecCZDQiOlc0Z+i43strOL5uTaRDwdrbMPmGsfiATNBPq2CZQSCGFSaufnXF0POYy/tEkWrKWy2u5Nnm98N8icuX4L6vcpaM8TCCc+E8ANLcoTYtByUq5Y+NsWXHwNgG3TKuMSR9hZPby9zQD8fkRleJYJ1tYXO5O+axS2EylAYJr8eNLvwGrt0BezR8WpeUy+fnay1T5+MtUbcLu1dTzzWeu9LcMCP3rmqfLNbGB1CrMjvKbdT2ok9/ZHpzln+UYtnw1nq3EiH77adCDF1Q==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: family-day-prod
    type: kubernetes.io/dockerconfigjson
