apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: family-day-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: public
  rules:
    - host: family-day.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: family-day-web
                port:
                  number: 80